// <auto-generated />
using System;
using IoTAssesment.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IoTAssesment.Migrations
{
    [DbContext(typeof(IoTDeviceContext))]
    [Migration("20251108122440_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IoTAssesment.Models.DeviceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("DeviceId");

                    b.HasIndex("Timestamp");

                    b.ToTable("DeviceLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "Created",
                            Description = "Device created and registered",
                            DeviceId = 1,
                            Status = "Success",
                            Timestamp = new DateTime(2025, 10, 9, 12, 24, 39, 728, DateTimeKind.Utc).AddTicks(7402)
                        },
                        new
                        {
                            Id = 2,
                            Action = "StatusUpdate",
                            Description = "Device came online",
                            DeviceId = 1,
                            Status = "Success",
                            Timestamp = new DateTime(2025, 11, 8, 12, 19, 39, 728, DateTimeKind.Utc).AddTicks(7404)
                        },
                        new
                        {
                            Id = 3,
                            Action = "Created",
                            Description = "Device created and registered",
                            DeviceId = 2,
                            Status = "Success",
                            Timestamp = new DateTime(2025, 9, 24, 12, 24, 39, 728, DateTimeKind.Utc).AddTicks(7406)
                        },
                        new
                        {
                            Id = 4,
                            Action = "FirmwareUpdate",
                            Description = "Firmware updated to version 2.1.0",
                            DeviceId = 2,
                            Status = "Success",
                            Timestamp = new DateTime(2025, 10, 29, 12, 24, 39, 728, DateTimeKind.Utc).AddTicks(7407)
                        },
                        new
                        {
                            Id = 5,
                            Action = "Created",
                            Description = "Device created and registered",
                            DeviceId = 3,
                            Status = "Success",
                            Timestamp = new DateTime(2025, 9, 9, 12, 24, 39, 728, DateTimeKind.Utc).AddTicks(7408)
                        },
                        new
                        {
                            Id = 6,
                            Action = "StatusUpdate",
                            Description = "Device went offline - low battery",
                            DeviceId = 3,
                            Status = "Warning",
                            Timestamp = new DateTime(2025, 11, 8, 10, 24, 39, 728, DateTimeKind.Utc).AddTicks(7411)
                        },
                        new
                        {
                            Id = 7,
                            Action = "Created",
                            Description = "Device created and registered",
                            DeviceId = 4,
                            Status = "Success",
                            Timestamp = new DateTime(2025, 10, 24, 12, 24, 39, 728, DateTimeKind.Utc).AddTicks(7412)
                        },
                        new
                        {
                            Id = 8,
                            Action = "Created",
                            Description = "Device created and registered",
                            DeviceId = 5,
                            Status = "Success",
                            Timestamp = new DateTime(2025, 10, 19, 12, 24, 39, 728, DateTimeKind.Utc).AddTicks(7413)
                        },
                        new
                        {
                            Id = 9,
                            Action = "StatusUpdate",
                            Description = "Device went offline - battery critically low",
                            DeviceId = 5,
                            Status = "Critical",
                            Timestamp = new DateTime(2025, 11, 7, 12, 24, 39, 728, DateTimeKind.Utc).AddTicks(7415)
                        });
                });

            modelBuilder.Entity("IoTAssesment.Models.IoTDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("BatteryLevel")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double?>("Humidity")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("Temperature")
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceType");

                    b.HasIndex("IsOnline");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("IoTDevices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatteryLevel = 85.5,
                            CreatedAt = new DateTime(2025, 10, 9, 12, 24, 39, 728, DateTimeKind.Utc).AddTicks(7310),
                            Description = "Monitors temperature in warehouse storage area",
                            DeviceType = "Temperature Sensor",
                            FirmwareVersion = "1.2.3",
                            Humidity = 45.200000000000003,
                            IsOnline = true,
                            LastSeen = new DateTime(2025, 11, 8, 12, 19, 39, 728, DateTimeKind.Utc).AddTicks(7302),
                            Location = "Warehouse A - Zone 1",
                            Name = "Temperature Sensor - Warehouse A",
                            SerialNumber = "TEMP-001-WHA",
                            Temperature = 22.5,
                            UpdatedAt = new DateTime(2025, 11, 8, 12, 19, 39, 728, DateTimeKind.Utc).AddTicks(7312)
                        },
                        new
                        {
                            Id = 2,
                            BatteryLevel = 92.0,
                            CreatedAt = new DateTime(2025, 9, 24, 12, 24, 39, 728, DateTimeKind.Utc).AddTicks(7317),
                            Description = "Electronic lock for main building entrance",
                            DeviceType = "Access Control",
                            FirmwareVersion = "2.1.0",
                            IsOnline = true,
                            LastSeen = new DateTime(2025, 11, 8, 12, 22, 39, 728, DateTimeKind.Utc).AddTicks(7317),
                            Location = "Building Main Entrance",
                            Name = "Smart Lock - Main Entrance",
                            SerialNumber = "LOCK-002-ME",
                            UpdatedAt = new DateTime(2025, 11, 8, 12, 22, 39, 728, DateTimeKind.Utc).AddTicks(7318)
                        },
                        new
                        {
                            Id = 3,
                            BatteryLevel = 15.199999999999999,
                            CreatedAt = new DateTime(2025, 9, 9, 12, 24, 39, 728, DateTimeKind.Utc).AddTicks(7322),
                            Description = "Monitors humidity levels in the server room",
                            DeviceType = "Environmental Sensor",
                            FirmwareVersion = "1.0.8",
                            Humidity = 35.799999999999997,
                            IsOnline = false,
                            LastSeen = new DateTime(2025, 11, 8, 10, 24, 39, 728, DateTimeKind.Utc).AddTicks(7321),
                            Location = "Server Room - Floor 2",
                            Name = "Humidity Monitor - Server Room",
                            SerialNumber = "HUM-003-SR",
                            Temperature = 18.699999999999999,
                            UpdatedAt = new DateTime(2025, 11, 8, 10, 24, 39, 728, DateTimeKind.Utc).AddTicks(7322)
                        },
                        new
                        {
                            Id = 4,
                            BatteryLevel = 78.900000000000006,
                            CreatedAt = new DateTime(2025, 10, 24, 12, 24, 39, 728, DateTimeKind.Utc).AddTicks(7326),
                            Description = "Detects motion in the parking lot area",
                            DeviceType = "Security Sensor",
                            FirmwareVersion = "3.2.1",
                            IsOnline = true,
                            LastSeen = new DateTime(2025, 11, 8, 12, 23, 39, 728, DateTimeKind.Utc).AddTicks(7325),
                            Location = "Parking Lot - North Side",
                            Name = "Motion Detector - Parking Lot",
                            SerialNumber = "MOT-004-PL",
                            UpdatedAt = new DateTime(2025, 11, 8, 12, 23, 39, 728, DateTimeKind.Utc).AddTicks(7326)
                        },
                        new
                        {
                            Id = 5,
                            BatteryLevel = 5.0999999999999996,
                            CreatedAt = new DateTime(2025, 10, 19, 12, 24, 39, 728, DateTimeKind.Utc).AddTicks(7330),
                            Description = "Monitors air quality in the main office area",
                            DeviceType = "Environmental Sensor",
                            FirmwareVersion = "1.5.2",
                            Humidity = 50.299999999999997,
                            IsOnline = false,
                            LastSeen = new DateTime(2025, 11, 7, 12, 24, 39, 728, DateTimeKind.Utc).AddTicks(7329),
                            Location = "Main Office - Floor 1",
                            Name = "Air Quality Monitor - Office",
                            SerialNumber = "AIR-005-OF",
                            Temperature = 21.199999999999999,
                            UpdatedAt = new DateTime(2025, 11, 7, 12, 24, 39, 728, DateTimeKind.Utc).AddTicks(7330)
                        });
                });

            modelBuilder.Entity("IoTAssesment.Models.DeviceLog", b =>
                {
                    b.HasOne("IoTAssesment.Models.IoTDevice", "Device")
                        .WithMany("DeviceLogs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("IoTAssesment.Models.IoTDevice", b =>
                {
                    b.Navigation("DeviceLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
