// <auto-generated />
using System;
using IoTAssesment.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IoTAssesment.Migrations
{
    [DbContext(typeof(IoTDeviceContext))]
    partial class IoTDeviceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IoTAssesment.Models.DeviceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("DeviceId");

                    b.HasIndex("Timestamp");

                    b.ToTable("DeviceLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "Created",
                            Description = "Device created and registered",
                            DeviceId = 1,
                            Status = "Success",
                            Timestamp = new DateTime(2025, 10, 9, 13, 31, 58, 545, DateTimeKind.Utc).AddTicks(379)
                        },
                        new
                        {
                            Id = 2,
                            Action = "StatusUpdate",
                            Description = "Device came online",
                            DeviceId = 1,
                            Status = "Success",
                            Timestamp = new DateTime(2025, 11, 8, 13, 26, 58, 545, DateTimeKind.Utc).AddTicks(382)
                        },
                        new
                        {
                            Id = 3,
                            Action = "Created",
                            Description = "Device created and registered",
                            DeviceId = 2,
                            Status = "Success",
                            Timestamp = new DateTime(2025, 9, 24, 13, 31, 58, 545, DateTimeKind.Utc).AddTicks(383)
                        },
                        new
                        {
                            Id = 4,
                            Action = "FirmwareUpdate",
                            Description = "Firmware updated to version 2.1.0",
                            DeviceId = 2,
                            Status = "Success",
                            Timestamp = new DateTime(2025, 10, 29, 13, 31, 58, 545, DateTimeKind.Utc).AddTicks(385)
                        },
                        new
                        {
                            Id = 5,
                            Action = "Created",
                            Description = "Device created and registered",
                            DeviceId = 3,
                            Status = "Success",
                            Timestamp = new DateTime(2025, 9, 9, 13, 31, 58, 545, DateTimeKind.Utc).AddTicks(424)
                        },
                        new
                        {
                            Id = 6,
                            Action = "StatusUpdate",
                            Description = "Device went offline - low battery",
                            DeviceId = 3,
                            Status = "Warning",
                            Timestamp = new DateTime(2025, 11, 8, 11, 31, 58, 545, DateTimeKind.Utc).AddTicks(426)
                        });
                });

            modelBuilder.Entity("IoTAssesment.Models.IoTDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ConfigurationJson")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ConnectionStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastMqttConnection")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ManufacturerName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ModelNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MqttPasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MqttUsername")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceType");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsOnline");

                    b.HasIndex("Location");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("IoTDevices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApiKey = "",
                            ClientId = "",
                            ConnectionStatus = "Never Connected",
                            CreatedAt = new DateTime(2025, 10, 9, 13, 31, 58, 545, DateTimeKind.Utc).AddTicks(352),
                            Description = "Monitors temperature in warehouse storage area",
                            DeviceType = "Temperature Sensor",
                            FirmwareVersion = "1.2.3",
                            IsActive = true,
                            IsOnline = true,
                            LastMqttConnection = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSeen = new DateTime(2025, 11, 8, 13, 26, 58, 545, DateTimeKind.Utc).AddTicks(347),
                            Location = "Warehouse A - Zone 1",
                            ManufacturerName = "TechSensors Inc",
                            ModelNumber = "TS-100",
                            Name = "Temperature Sensor - Warehouse A",
                            SerialNumber = "TEMP-001-WHA",
                            UpdatedAt = new DateTime(2025, 11, 8, 13, 26, 58, 545, DateTimeKind.Utc).AddTicks(354)
                        },
                        new
                        {
                            Id = 2,
                            ApiKey = "",
                            ClientId = "",
                            ConnectionStatus = "Never Connected",
                            CreatedAt = new DateTime(2025, 9, 24, 13, 31, 58, 545, DateTimeKind.Utc).AddTicks(359),
                            Description = "Electronic lock for main building entrance",
                            DeviceType = "Access Control",
                            FirmwareVersion = "2.1.0",
                            IsActive = true,
                            IsOnline = true,
                            LastMqttConnection = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSeen = new DateTime(2025, 11, 8, 13, 29, 58, 545, DateTimeKind.Utc).AddTicks(358),
                            Location = "Building Main Entrance",
                            ManufacturerName = "SecureTech",
                            ModelNumber = "SL-200",
                            Name = "Smart Lock - Main Entrance",
                            SerialNumber = "LOCK-002-ME",
                            UpdatedAt = new DateTime(2025, 11, 8, 13, 29, 58, 545, DateTimeKind.Utc).AddTicks(359)
                        },
                        new
                        {
                            Id = 3,
                            ApiKey = "",
                            ClientId = "",
                            ConnectionStatus = "Never Connected",
                            CreatedAt = new DateTime(2025, 9, 9, 13, 31, 58, 545, DateTimeKind.Utc).AddTicks(363),
                            Description = "Monitors humidity levels in the server room",
                            DeviceType = "Environmental Sensor",
                            FirmwareVersion = "1.0.8",
                            IsActive = true,
                            IsOnline = false,
                            LastMqttConnection = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSeen = new DateTime(2025, 11, 8, 11, 31, 58, 545, DateTimeKind.Utc).AddTicks(362),
                            Location = "Server Room - Floor 2",
                            ManufacturerName = "EnviroSense",
                            ModelNumber = "ES-300",
                            Name = "Humidity Monitor - Server Room",
                            SerialNumber = "HUM-003-SR",
                            UpdatedAt = new DateTime(2025, 11, 8, 11, 31, 58, 545, DateTimeKind.Utc).AddTicks(363)
                        });
                });

            modelBuilder.Entity("IoTAssesment.Models.KeyDictionary", b =>
                {
                    b.Property<int>("KeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KeyId"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<double?>("MinValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValidationRules")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("KeyId");

                    b.HasIndex("Category");

                    b.HasIndex("DataType");

                    b.HasIndex("IsActive");

                    b.HasIndex("KeyName")
                        .IsUnique();

                    b.ToTable("KeyDictionaries");

                    b.HasData(
                        new
                        {
                            KeyId = 1,
                            Category = "sensor",
                            CreatedAt = new DateTime(2025, 11, 8, 13, 31, 58, 545, DateTimeKind.Utc).AddTicks(267),
                            DataType = "double",
                            Description = "Device battery level percentage",
                            IsActive = true,
                            IsRequired = false,
                            KeyName = "battery_level",
                            MaxValue = 100.0,
                            MinValue = 0.0,
                            Unit = "%",
                            UpdatedAt = new DateTime(2025, 11, 8, 13, 31, 58, 545, DateTimeKind.Utc).AddTicks(268)
                        },
                        new
                        {
                            KeyId = 2,
                            Category = "sensor",
                            CreatedAt = new DateTime(2025, 11, 8, 13, 31, 58, 545, DateTimeKind.Utc).AddTicks(275),
                            DataType = "double",
                            Description = "Temperature reading",
                            IsActive = true,
                            IsRequired = false,
                            KeyName = "temperature",
                            MaxValue = 100.0,
                            MinValue = -50.0,
                            Unit = "°C",
                            UpdatedAt = new DateTime(2025, 11, 8, 13, 31, 58, 545, DateTimeKind.Utc).AddTicks(275)
                        },
                        new
                        {
                            KeyId = 3,
                            Category = "sensor",
                            CreatedAt = new DateTime(2025, 11, 8, 13, 31, 58, 545, DateTimeKind.Utc).AddTicks(277),
                            DataType = "double",
                            Description = "Humidity percentage",
                            IsActive = true,
                            IsRequired = false,
                            KeyName = "humidity",
                            MaxValue = 100.0,
                            MinValue = 0.0,
                            Unit = "%",
                            UpdatedAt = new DateTime(2025, 11, 8, 13, 31, 58, 545, DateTimeKind.Utc).AddTicks(277)
                        },
                        new
                        {
                            KeyId = 4,
                            Category = "status",
                            CreatedAt = new DateTime(2025, 11, 8, 13, 31, 58, 545, DateTimeKind.Utc).AddTicks(279),
                            DataType = "long",
                            Description = "Signal strength indicator",
                            IsActive = true,
                            IsRequired = false,
                            KeyName = "signal_strength",
                            MaxValue = 0.0,
                            MinValue = -120.0,
                            Unit = "dBm",
                            UpdatedAt = new DateTime(2025, 11, 8, 13, 31, 58, 545, DateTimeKind.Utc).AddTicks(279)
                        },
                        new
                        {
                            KeyId = 5,
                            Category = "metadata",
                            CreatedAt = new DateTime(2025, 11, 8, 13, 31, 58, 545, DateTimeKind.Utc).AddTicks(281),
                            DataType = "string",
                            Description = "Current firmware version",
                            IsActive = true,
                            IsRequired = false,
                            KeyName = "firmware_version",
                            UpdatedAt = new DateTime(2025, 11, 8, 13, 31, 58, 545, DateTimeKind.Utc).AddTicks(281)
                        },
                        new
                        {
                            KeyId = 6,
                            Category = "status",
                            CreatedAt = new DateTime(2025, 11, 8, 13, 31, 58, 545, DateTimeKind.Utc).AddTicks(283),
                            DataType = "string",
                            Description = "Current device operational status",
                            IsActive = true,
                            IsRequired = false,
                            KeyName = "device_status",
                            UpdatedAt = new DateTime(2025, 11, 8, 13, 31, 58, 545, DateTimeKind.Utc).AddTicks(283)
                        },
                        new
                        {
                            KeyId = 7,
                            Category = "status",
                            CreatedAt = new DateTime(2025, 11, 8, 13, 31, 58, 545, DateTimeKind.Utc).AddTicks(284),
                            DataType = "long",
                            Description = "Device uptime in seconds",
                            IsActive = true,
                            IsRequired = false,
                            KeyName = "uptime",
                            MinValue = 0.0,
                            Unit = "seconds",
                            UpdatedAt = new DateTime(2025, 11, 8, 13, 31, 58, 545, DateTimeKind.Utc).AddTicks(285)
                        },
                        new
                        {
                            KeyId = 8,
                            Category = "performance",
                            CreatedAt = new DateTime(2025, 11, 8, 13, 31, 58, 545, DateTimeKind.Utc).AddTicks(286),
                            DataType = "double",
                            Description = "Memory usage percentage",
                            IsActive = true,
                            IsRequired = false,
                            KeyName = "memory_usage",
                            MaxValue = 100.0,
                            MinValue = 0.0,
                            Unit = "%",
                            UpdatedAt = new DateTime(2025, 11, 8, 13, 31, 58, 545, DateTimeKind.Utc).AddTicks(286)
                        },
                        new
                        {
                            KeyId = 9,
                            Category = "performance",
                            CreatedAt = new DateTime(2025, 11, 8, 13, 31, 58, 545, DateTimeKind.Utc).AddTicks(287),
                            DataType = "double",
                            Description = "CPU usage percentage",
                            IsActive = true,
                            IsRequired = false,
                            KeyName = "cpu_usage",
                            MaxValue = 100.0,
                            MinValue = 0.0,
                            Unit = "%",
                            UpdatedAt = new DateTime(2025, 11, 8, 13, 31, 58, 545, DateTimeKind.Utc).AddTicks(288)
                        },
                        new
                        {
                            KeyId = 10,
                            Category = "status",
                            CreatedAt = new DateTime(2025, 11, 8, 13, 31, 58, 545, DateTimeKind.Utc).AddTicks(290),
                            DataType = "long",
                            Description = "Number of errors since last reset",
                            IsActive = true,
                            IsRequired = false,
                            KeyName = "error_count",
                            MinValue = 0.0,
                            UpdatedAt = new DateTime(2025, 11, 8, 13, 31, 58, 545, DateTimeKind.Utc).AddTicks(290)
                        },
                        new
                        {
                            KeyId = 11,
                            Category = "location",
                            CreatedAt = new DateTime(2025, 11, 8, 13, 31, 58, 545, DateTimeKind.Utc).AddTicks(291),
                            DataType = "json",
                            Description = "GPS coordinates",
                            IsActive = true,
                            IsRequired = false,
                            KeyName = "location_coordinates",
                            UpdatedAt = new DateTime(2025, 11, 8, 13, 31, 58, 545, DateTimeKind.Utc).AddTicks(291)
                        },
                        new
                        {
                            KeyId = 12,
                            Category = "config",
                            CreatedAt = new DateTime(2025, 11, 8, 13, 31, 58, 545, DateTimeKind.Utc).AddTicks(292),
                            DataType = "json",
                            Description = "Device configuration settings",
                            IsActive = true,
                            IsRequired = false,
                            KeyName = "configuration",
                            UpdatedAt = new DateTime(2025, 11, 8, 13, 31, 58, 545, DateTimeKind.Utc).AddTicks(292)
                        });
                });

            modelBuilder.Entity("IoTAssesment.Models.Telemetry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Context")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double?>("DblValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<string>("JsonValue")
                        .HasColumnType("jsonb");

                    b.Property<int>("KeyId")
                        .HasColumnType("integer");

                    b.Property<long?>("LongValue")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PartitionDate")
                        .HasColumnType("date")
                        .HasColumnName("partition_date");

                    b.Property<string>("Quality")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StrValue")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KeyId");

                    b.HasIndex("Quality");

                    b.HasIndex("Timestamp");

                    b.HasIndex("PartitionDate", "DeviceId");

                    b.HasIndex("DeviceId", "KeyId", "Timestamp");

                    b.ToTable("Telemetries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DblValue = 22.5,
                            DeviceId = 1,
                            KeyId = 2,
                            PartitionDate = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Quality = "Good",
                            Timestamp = new DateTime(2025, 11, 8, 12, 31, 58, 545, DateTimeKind.Utc).AddTicks(441)
                        },
                        new
                        {
                            Id = 2L,
                            DblValue = 85.5,
                            DeviceId = 1,
                            KeyId = 1,
                            PartitionDate = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Quality = "Good",
                            Timestamp = new DateTime(2025, 11, 8, 12, 31, 58, 545, DateTimeKind.Utc).AddTicks(441)
                        },
                        new
                        {
                            Id = 4L,
                            DblValue = 23.0,
                            DeviceId = 1,
                            KeyId = 2,
                            PartitionDate = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Quality = "Good",
                            Timestamp = new DateTime(2025, 11, 8, 12, 36, 58, 545, DateTimeKind.Utc).AddTicks(441)
                        },
                        new
                        {
                            Id = 5L,
                            DblValue = 85.400000000000006,
                            DeviceId = 1,
                            KeyId = 1,
                            PartitionDate = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Quality = "Good",
                            Timestamp = new DateTime(2025, 11, 8, 12, 36, 58, 545, DateTimeKind.Utc).AddTicks(441)
                        },
                        new
                        {
                            Id = 7L,
                            DblValue = 23.5,
                            DeviceId = 1,
                            KeyId = 2,
                            PartitionDate = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Quality = "Good",
                            Timestamp = new DateTime(2025, 11, 8, 12, 41, 58, 545, DateTimeKind.Utc).AddTicks(441)
                        },
                        new
                        {
                            Id = 8L,
                            DblValue = 85.299999999999997,
                            DeviceId = 1,
                            KeyId = 1,
                            PartitionDate = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Quality = "Good",
                            Timestamp = new DateTime(2025, 11, 8, 12, 41, 58, 545, DateTimeKind.Utc).AddTicks(441)
                        },
                        new
                        {
                            Id = 10L,
                            DblValue = 24.0,
                            DeviceId = 1,
                            KeyId = 2,
                            PartitionDate = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Quality = "Good",
                            Timestamp = new DateTime(2025, 11, 8, 12, 46, 58, 545, DateTimeKind.Utc).AddTicks(441)
                        },
                        new
                        {
                            Id = 11L,
                            DblValue = 85.200000000000003,
                            DeviceId = 1,
                            KeyId = 1,
                            PartitionDate = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Quality = "Good",
                            Timestamp = new DateTime(2025, 11, 8, 12, 46, 58, 545, DateTimeKind.Utc).AddTicks(441)
                        },
                        new
                        {
                            Id = 13L,
                            DblValue = 24.5,
                            DeviceId = 1,
                            KeyId = 2,
                            PartitionDate = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Quality = "Good",
                            Timestamp = new DateTime(2025, 11, 8, 12, 51, 58, 545, DateTimeKind.Utc).AddTicks(441)
                        },
                        new
                        {
                            Id = 14L,
                            DblValue = 85.099999999999994,
                            DeviceId = 1,
                            KeyId = 1,
                            PartitionDate = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Quality = "Good",
                            Timestamp = new DateTime(2025, 11, 8, 12, 51, 58, 545, DateTimeKind.Utc).AddTicks(441)
                        },
                        new
                        {
                            Id = 16L,
                            DblValue = 25.0,
                            DeviceId = 1,
                            KeyId = 2,
                            PartitionDate = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Quality = "Good",
                            Timestamp = new DateTime(2025, 11, 8, 12, 56, 58, 545, DateTimeKind.Utc).AddTicks(441)
                        },
                        new
                        {
                            Id = 17L,
                            DblValue = 85.0,
                            DeviceId = 1,
                            KeyId = 1,
                            PartitionDate = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Quality = "Good",
                            Timestamp = new DateTime(2025, 11, 8, 12, 56, 58, 545, DateTimeKind.Utc).AddTicks(441)
                        },
                        new
                        {
                            Id = 19L,
                            DblValue = 25.5,
                            DeviceId = 1,
                            KeyId = 2,
                            PartitionDate = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Quality = "Good",
                            Timestamp = new DateTime(2025, 11, 8, 13, 1, 58, 545, DateTimeKind.Utc).AddTicks(441)
                        },
                        new
                        {
                            Id = 20L,
                            DblValue = 84.900000000000006,
                            DeviceId = 1,
                            KeyId = 1,
                            PartitionDate = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Quality = "Good",
                            Timestamp = new DateTime(2025, 11, 8, 13, 1, 58, 545, DateTimeKind.Utc).AddTicks(441)
                        },
                        new
                        {
                            Id = 22L,
                            DblValue = 26.0,
                            DeviceId = 1,
                            KeyId = 2,
                            PartitionDate = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Quality = "Good",
                            Timestamp = new DateTime(2025, 11, 8, 13, 6, 58, 545, DateTimeKind.Utc).AddTicks(441)
                        },
                        new
                        {
                            Id = 23L,
                            DblValue = 84.799999999999997,
                            DeviceId = 1,
                            KeyId = 1,
                            PartitionDate = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Quality = "Good",
                            Timestamp = new DateTime(2025, 11, 8, 13, 6, 58, 545, DateTimeKind.Utc).AddTicks(441)
                        },
                        new
                        {
                            Id = 25L,
                            DblValue = 26.5,
                            DeviceId = 1,
                            KeyId = 2,
                            PartitionDate = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Quality = "Good",
                            Timestamp = new DateTime(2025, 11, 8, 13, 11, 58, 545, DateTimeKind.Utc).AddTicks(441)
                        },
                        new
                        {
                            Id = 26L,
                            DblValue = 84.700000000000003,
                            DeviceId = 1,
                            KeyId = 1,
                            PartitionDate = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Quality = "Good",
                            Timestamp = new DateTime(2025, 11, 8, 13, 11, 58, 545, DateTimeKind.Utc).AddTicks(441)
                        },
                        new
                        {
                            Id = 28L,
                            DblValue = 27.0,
                            DeviceId = 1,
                            KeyId = 2,
                            PartitionDate = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Quality = "Good",
                            Timestamp = new DateTime(2025, 11, 8, 13, 16, 58, 545, DateTimeKind.Utc).AddTicks(441)
                        },
                        new
                        {
                            Id = 29L,
                            DblValue = 84.599999999999994,
                            DeviceId = 1,
                            KeyId = 1,
                            PartitionDate = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Quality = "Good",
                            Timestamp = new DateTime(2025, 11, 8, 13, 16, 58, 545, DateTimeKind.Utc).AddTicks(441)
                        },
                        new
                        {
                            Id = 50L,
                            DeviceId = 2,
                            KeyId = 6,
                            PartitionDate = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Quality = "Good",
                            StrValue = "Operational",
                            Timestamp = new DateTime(2025, 11, 8, 12, 31, 58, 545, DateTimeKind.Utc).AddTicks(441)
                        },
                        new
                        {
                            Id = 51L,
                            DeviceId = 2,
                            KeyId = 6,
                            PartitionDate = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Quality = "Good",
                            StrValue = "Operational",
                            Timestamp = new DateTime(2025, 11, 8, 12, 41, 58, 545, DateTimeKind.Utc).AddTicks(441)
                        },
                        new
                        {
                            Id = 52L,
                            DeviceId = 2,
                            KeyId = 6,
                            PartitionDate = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Quality = "Good",
                            StrValue = "Operational",
                            Timestamp = new DateTime(2025, 11, 8, 12, 51, 58, 545, DateTimeKind.Utc).AddTicks(441)
                        },
                        new
                        {
                            Id = 53L,
                            DeviceId = 2,
                            KeyId = 6,
                            PartitionDate = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Quality = "Good",
                            StrValue = "Operational",
                            Timestamp = new DateTime(2025, 11, 8, 13, 1, 58, 545, DateTimeKind.Utc).AddTicks(441)
                        },
                        new
                        {
                            Id = 54L,
                            DeviceId = 2,
                            KeyId = 6,
                            PartitionDate = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Quality = "Good",
                            StrValue = "Operational",
                            Timestamp = new DateTime(2025, 11, 8, 13, 11, 58, 545, DateTimeKind.Utc).AddTicks(441)
                        });
                });

            modelBuilder.Entity("IoTAssesment.Models.DeviceLog", b =>
                {
                    b.HasOne("IoTAssesment.Models.IoTDevice", "Device")
                        .WithMany("DeviceLogs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("IoTAssesment.Models.Telemetry", b =>
                {
                    b.HasOne("IoTAssesment.Models.IoTDevice", "Device")
                        .WithMany("Telemetries")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IoTAssesment.Models.KeyDictionary", "Key")
                        .WithMany("Telemetries")
                        .HasForeignKey("KeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Key");
                });

            modelBuilder.Entity("IoTAssesment.Models.IoTDevice", b =>
                {
                    b.Navigation("DeviceLogs");

                    b.Navigation("Telemetries");
                });

            modelBuilder.Entity("IoTAssesment.Models.KeyDictionary", b =>
                {
                    b.Navigation("Telemetries");
                });
#pragma warning restore 612, 618
        }
    }
}
